### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by KhmerRun** [italocoin-project/italocoin#7]
Hello, I got error during make

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libboost_filesystem.a(operations.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libboost_filesystem.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/blockchain_utilities/CMakeFiles/blockchain_usage.dir/build.make:132: recipe for target 'bin/italocoin-blockchain-usage' failed
make[3]: *** [bin/italocoin-blockchain-usage] Error 1
make[3]: Leaving directory '/home/lalalolo/daemon-italocoin/italocoin-20180420/build/release'
CMakeFiles/Makefile2:3053: recipe for target 'src/blockchain_utilities/CMakeFiles/blockchain_usage.dir/all' failed
make[2]: *** [src/blockchain_utilities/CMakeFiles/blockchain_usage.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/lalalolo/daemon-italocoin/italocoin-20180420/build/release'
[ 88%] Built target obj_wallet
make[2]: Leaving directory '/home/lalalolo/daemon-italocoin/italocoin-20180420/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/lalalolo/daemon-italocoin/italocoin-20180420/build/release'
Makefile:68: recipe for target 'release-static' failed
make: *** [release-static] Error 2

**Comment by italocoin-project** [comment]
Recompile boost with fpic, do you really need release-static? You can download binaries from latest release.

**Comment by KhmerRun** [comment]
Thank you. Just make done.
